# Generated by Django 3.1.4 on 2021-03-20 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_index', models.IntegerField(blank=True)),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('realtor_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True)),
                ('email', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(blank=True)),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
