# Generated by Django 3.1.4 on 2021-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='purchase_index',
            field=models.IntegerField(),
        ),
    ]
