# Generated by Django 3.1.4 on 2021-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210320_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='purchase_index',
            field=models.CharField(max_length=4),
        ),
    ]
